os: linux
language: c

jobs:
  include:
    - env: NGXVER=head
      compiler: gcc
    - env: NGXVER=1.18.0
      compiler: gcc
    - env: NGXVER=1.16.1
      compiler: gcc
    - env: NGXVER=1.14.2
      compiler: gcc
    - env: NGXVER=1.12.2
      compiler: gcc
  allow_failures:
    - env: NGXVER=head

before_install:
  - |
    set -e
    cpanm -v --notest --local-lib=~/perl5 local::lib Test::Nginx &&
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
    set +e

install:
  - |
    set -e
    if [ "$NGXVER" == head ]
    then
        git clone https://github.com/nginx/nginx.git nginx-head
    else
        wget http://nginx.org/download/nginx-${NGXVER}.tar.gz &&
            tar xzvf nginx-${NGXVER}.tar.gz
    fi
    git clone https://github.com/openresty/echo-nginx-module.git
    set +e

script:
  - |
    set -e
    cd nginx-${NGXVER}/
    if [ "$NGXVER" == head ]
    then
        NGX_CONFIGURE=./auto/configure
    else
        NGX_CONFIGURE=./configure
    fi
    $NGX_CONFIGURE --add-module=.. --add-module=../echo-nginx-module
    make -j2
    export PATH=$(pwd)/objs:$PATH
    cd -
    cd test
    set +e
    prove -r t

