name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        nginx: [1.16.1, 1.18.0, 1.20.2, 1.22.1, 1.24.0, 1.26.2]
        nginx-easy-context: ['1.0']
        experimental: [false]
        include:
          - nginx: head
            nginx-easy-context: '1.0'
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prove
        uses: perl-actions/install-with-cpanm@v1.7
        with:
          install: "Test::Nginx"
          tests: false
      - name: Install and test
        env:
          NGXVER: ${{ matrix.nginx }}
          NGXEASYCTXVER: ${{ matrix.nginx-easy-context }}
        run: |
          if [ "$NGXVER" = head ]
          then
              git clone https://github.com/nginx/nginx.git nginx-head
          else
              wget http://nginx.org/download/nginx-${NGXVER}.tar.gz &&
                  tar xzvf nginx-${NGXVER}.tar.gz
          fi
          git clone https://github.com/openresty/echo-nginx-module.git
          cd nginx-${NGXVER}/
          if [ "$NGXVER" = head ]
          then
              NGX_CONFIGURE=./auto/configure
          else
              NGX_CONFIGURE=./configure
          fi
          $NGX_CONFIGURE --add-module=.. --add-module=../echo-nginx-module
          make -j2
          export PATH="$(pwd)/objs:$PATH"
          cd -
          cd test
          prove t/basic.t t/timeout.t
          cd -
          wget "https://github.com/lyokha/nginx-easy-context/"`
              `"archive/refs/tags/$NGXEASYCTXVER.tar.gz" \
               -O "nginx-easy-context-$NGXEASYCTXVER.tar.gz" &&
                  tar xzvf "nginx-easy-context-$NGXEASYCTXVER.tar.gz"
          sed -i 's/# \('`
              `'NGX_HTTP_COMBINED_UPSTREAMS_UPSTRAND_PERSISTENT_INTERCEPT_CTX'`
              `'=1\)/\1/' config
          cd nginx-${NGXVER}/
          $NGX_CONFIGURE --add-module=../nginx-easy-context-$NGXEASYCTXVER \
              --add-module=.. --add-module=../echo-nginx-module
          make -j2
          cd -
          cd test
          prove t/redirect_upstrand_failover_location.t

