name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
       include:
         - nginx: head
           experimental: true
         - nginx: 1.18.0
           experimental: false
         - nginx: 1.16.1
           experimental: false
         - nginx: 1.14.2
           experimental: false
         - nginx: 1.12.2
           experimental: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install prove
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: "Test::Nginx"
          tests: false
      - name: Install and test
        env:
          NGXVER: ${{ matrix.nginx }}
        run: |
          set -e
          if [ "$NGXVER" == head ]
          then
              git clone https://github.com/nginx/nginx.git nginx-head
          else
              wget http://nginx.org/download/nginx-${NGXVER}.tar.gz &&
                  tar xzvf nginx-${NGXVER}.tar.gz
          fi
          git clone https://github.com/openresty/echo-nginx-module.git
          cd nginx-${NGXVER}/
          if [ "$NGXVER" == head ]
          then
              NGX_CONFIGURE=./auto/configure
          else
              NGX_CONFIGURE=./configure
          fi
          $NGX_CONFIGURE --add-module=.. --add-module=../echo-nginx-module
          make -j2
          export PATH=$(pwd)/objs:$PATH
          cd -
          cd test
          set +e
          prove -r t

